title: Shanshan Gao's Homepage
page-top-title: Shanshan Gao
top-section-bg-text: Data Science
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Shanshan gao 2023-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/gas-1122
license-link:
  text: License
  href: https://github.com/gas-1122/gas-1122.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Shanshan Gao&ensp;|&ensp;高姗姗
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
